### PR TITLE
WIP: Complete support for Replica Set. Needs Automated tests and Travis Setup

### PR DESCRIPTION
**Pull request by emerleite**
So, I developed a complete support for Replica Set. You pass a list of hosts and it will try each one until connect. When connects, if the current is not the master, it will change to the right master to do the job. I did lots of manual tests on my machine (yes, works on my machine :p) and everything is perfect. It will be good if somebody else do tests.

This is the usage syntax:

``` elixir
{:ok, pid} = Mongo.start_link(database: "test", 
  hosts: [
    {"localhost", 27017}, 
    {"localhost", 27018}, 
    {"localhost", 27019}
  ])
```

Can anybody helps me to finish it to a state we can merge?

### CODE REVIEW

**Comment by ericmj** [comment]
This seems great, but we need tests of course. Unfortunately I cannot merge without tests.

**Comment by emerleite** [comment]
@ericmj is that why I need help to finish it and it's a WIP. Could you help me with this?

**Comment by ericmj** [comment]
Unfortunately I cannot help not any more than I could in the original PR and issue. I am currently focused on other things and there will be some time until I can spend time on this project.

**Comment by ericmj** [comment]
Closed in favor of the new PRs.

**Pull request closed without merging**
