### PR TITLE
Fix for trying to query the connection too soon

### LINKED ISSUE #158: after_connect not populating Topology.state.connection_pools in time
I'm using poolboy to start workers that make connections to Mongo.
If I send too many requests to poolboy and it spawns up new connections to Mongo, there is a timing issue where `state.connection_pools` in `Topology.ex` isn't populated in time because it receives messages out of order.

For example:

Mongo.ex
```
@spec start_link(Keyword.t) :: {:ok, pid} | {:error, Mongo.Error.t | term}
def start_link(opts) do
  res = Topology.start_link(opts)
  IO.inspect(res, label: "Started Mongo")
  res
end

@spec find(GenServer.server, collection, BSON.document, Keyword.t) :: cursor
def find(topology_pid, coll, filter, opts \\ []) do
  IO.inspect(topology_pid, label: "Finding")
  ...
end
```

Monitor.ex
```
@doc false
def connected(_connection, me, topology_pid) do
  IO.inspect(topology_pid, label: "Connected")
  GenServer.cast(topology_pid, {:connected, me})
end
```

Topology.ex
```
def handle_call({:connection, address}, _from, state) do
  IO.inspect(state.connection_pools, label: "Connection Pools #{inspect(self)}")
  {:reply, Map.fetch(state.connection_pools, address), state}
end
```

I will get output that looks like this:

```
Started Mongo: {:ok, #PID<0.2690.0>}
Finding: #PID<0.2690.0>
Connection Pools #PID<0.2690.0>: %{}
Connected: #PID<0.2690.0>
```

I believe the `after_connect` in DbConnection is handled after a pid is returned and poolboy starts using the pid before the `connected` is called in Topology which would result in an inbox for Topology looking like this:

```
:connection // called from connection_for_address
:connected
```

I recommend Monitor.init/1 be the following:

```
@doc false
  def init([server_description, topology_pid, heartbeat_frequency_ms, connection_opts]) do
    opts = # monitors don't authenticate and use the "admin" database
      connection_opts
      |> Keyword.put(:database, "admin")
      |> Keyword.put(:skip_auth, true)
      |> Keyword.put(:backoff_min, heartbeat_frequency_ms)
      |> Keyword.put(:backoff_max, heartbeat_frequency_ms)
      |> Keyword.put(:backoff_type, :rand)
      |> Keyword.put(:connection_type, :monitor)
      |> Keyword.put(:topology_pid, topology_pid)

    {:ok, pid} = DBConnection.start_link(Mongo.Protocol, opts)
    
    # Notify Topology that we are connected
    connected(pid, self(), topology_pid)
    
    :ok = GenServer.cast(self, :check)
    {:ok, %{
      connection_pid: pid,
      topology_pid: topology_pid,
      server_description: server_description,
      heartbeat_frequency_ms: heartbeat_frequency_ms,
      opts: opts
    }}
  end
```

Here we drop `after_connect` and call `connected` right away.

If you agree that I've identified the problem and accept the proposed solution, I can submit a pull request.

### PR DESCRIPTION
**Pull request by ankhers**
Fixes #158

### CODE REVIEW

**Comment by ankhers** [comment]
@Sailias, @gazoon Can you please test this branch to ensure that it fixed your issues?

**Comment by ankhers** [comment]
Actually, don't test yet. I still have things failing on my end.

**Comment by ankhers** [comment]
Alright, should be good to test.

**Comment by ankhers** [comment]
@Sailias The repo you linked in your ticket works for me under these changes.

**Comment by Sailias** [comment]
@ankhers does that mean the repo I linked didn’t work prior to the changes as you commented before (but may have deleted)?

**Comment by ankhers** [comment]
As in I was getting the error you mentioned before these changes. With these changes I am no longer getting an error.

**Pull request merged**
