### PR TITLE
Updating BSON.Timestamp to match BSON specification

### LINKED ISSUE #178: Timestamp Decoding Problem
When loading the following record with this library:
```json
{ "_id" : { "$oid" : "5a424f5b486aec571f69c58b" }, "identifier" : "617ce328-9ff8-4f24-a7f2-d30bb1cb3dea", "metadata" : {  }, "payload" : { "color" : "orange", "name" : "Cotton Shoes", "price" : 0.96 }, "serial_number" : 1, "type" : "Gengar", "version" : 1, "datetime" : { "$timestamp" : { "t" : 1514295131, "i" : 16 } } }
```

The timestamp seems to be incorrectly loaded:

```
13:36:53.978 [error] DB value %{"_id" => #BSON.ObjectId<5a425075486aec571f69c757>, "datetime" => #BSON.Timestamp<6503849275317813254>, "identifier" => "e9ce9ca4-5981-41ec-87ba-1b1c19cd1c35", "metadata" => %{}, "payload" => %{color: "salmon", name: "Sleek Shirt", price: 5.47}, "serial_number" => 1, "type" => "Kakuna", "version" => 1}
```

`#BSON.Timestamp<6503849275317813254>` isn't a valid epoch

### PR DESCRIPTION
**Pull request by rawkode**
Timestamps are 32bit epochs with a 32 bit ordinal

Fixes #178

### CODE REVIEW

**Comment by rawkode** [comment]
I was unable to actually run the test suite, as it would appear that the test helper script is missing a bunch of `--port 27001` from all the `System.cmd` calls.

Even adding them, all I got were time outs. This could definitely do with further documentation, as perhaps a docker-compose.yml

**Comment by rawkode** [comment]
Not sure what I've done wrong for the tests to fail, tried a few times

**Comment by ankhers** [comment]
Based on the test errors, you mixed up the value and the ordinal

```
  1) test decode (BSONTest)
     test/bson_test.exs:103
     Assertion with == failed
     code: decode(@bin17) == @map17
     lhs:  %{"m" => %BSON.Timestamp{ordinal: 12345678, value: 0}}
     rhs:  %{"m" => %BSON.Timestamp{ordinal: 0, value: 12345678}}
     stacktrace:
       test/bson_test.exs:120: (test)

  2) test encode (BSONTest)
     test/bson_test.exs:78
     Assertion with == failed
     code: encode(@timestamp_map_1) == @timestamp_bin_1
     lhs:  <<16, 0, 0, 0, 17, 113, 0, 37, 26, 91, 90, 12, 0, 0, 0, 0>>
     rhs:  <<16, 0, 0, 0, 17, 113, 0, 12, 0, 0, 0, 37, 26, 91, 90, 0>>
     stacktrace:
       test/bson_test.exs:100: (test)
```

**Comment by rawkode** [comment]
Fixed the ordering. Looks like one test failed because of an npm issue. This should be good to go 🎉

**Comment by ankhers** [comment]
Thank you for working on this!

**Pull request merged**
