### PR TITLE
WIP: Better replica sets

### LINKED ISSUE #144: Application will not start if one or more servers in the cluster are down
I am not 100% sure what part of the pipeline is broken here. But I think we should make connections to the monitors first, then make the actual connections the application will use based on which servers were connected to successfully.

### PR DESCRIPTION
**Pull request by ankhers**
This PR aims to better follow the [MongoDB server discovery and monitoring spec](https://github.com/mongodb/specifications/blob/master/source/server-discovery-and-monitoring/server-discovery-and-monitoring.rst#topologytype)

This is PR aims to resolve #144, #142 and #141. I believe there is overlap between those different issues.

### CODE REVIEW

**Comment by ankhers** [comment]
@ben-ic, @Arthien, @elie222 Would the three of you mind testing this branch to see if you are still having issues with your applications crashing / not starting when a Mongo node goes down?

**Comment by christianjgreen** [comment]
@ankhers sure!

**Comment by christianjgreen** [comment]
@ankhers Working here so far! Was able to stay connected

**Comment by ankhers** [comment]
Assuming no one mentions something about this not working correctly, I will merge it once the new version of the `db_connection` package is released.

**Comment by christianjgreen** [comment]
@ankhers what changes do you need from `db_connection`?

**Comment by ankhers** [comment]
@Arthien It has to do with how a not connected connection worked. In the current released version if you attempt to query against a not connected connection, it would raise an exception. This has been changed to return `{:error, exception}` instead. This was one of the issues that you were bumping up against when one or more servers in the MongoDB cluster were down.

This is important because we keep trying to query each of the servers in the cluster to see what its representation of the cluster looks like so that the driver can keep up to date on how things should be looking.

**Comment by ankhers** [comment]
@Arthien Can you test to see if this works for you still?

**Comment by ankhers** [comment]
ping @Arthien

**Comment by christianjgreen** [comment]
@ankhers I'll test this out today!

**Comment by ankhers** [comment]
Thanks!

**Comment by christianjgreen** [comment]
@ankhers Looking good. Scaling a 3 cluster replica set up and then down. Application did not restart and I was able to stay connected to at least one node.

**Comment by ankhers** [comment]
Good to hear. I will create a release for this branch shortly.

**Pull request merged**
