### PR TITLE
Support new crypto API -  hmac and mac

### PR DESCRIPTION
**Pull request by IgorPolyakov**
add support Erlang/OTP 24

original MR - https://github.com/elixir-mongo/mongodb/pull/360

### CODE REVIEW

**Comment by joeapearson** [comment]
@IgorPolyakov thanks for this; as it happens we already made some changes in #364 which among other things addressed this issue.  Please let us know if you think we should go any further!

**Comment by joeapearson** [comment]
@IgorPolyakov I hadn't noticed you've gone as far as to add nice backwards compatibility.  If you could solve the merge conflict then I'd be happy to merge this right in!  Thanks.

**Comment by IgorPolyakov** [comment]
@joeapearson Merge conflicts is resolved)

**Comment by joeapearson** [comment]
Looks good, thanks @IgorPolyakov

**Pull request merged**
