### PR TITLE
Server discovery

### PR DESCRIPTION
**Pull request by ankhers**
This is meant to replace #93. I will complete this feature unless the original submitters want to finish it off. This has a couple extra commits based on my couple comments at the end of the thread.

### CODE REVIEW

**Comment by ankhers** [comment]
The connection tests are currently not passing because the travis file no longer starts a mongo instance on port 27017. I will see if I can get that working.

There is also the issue with `Mongo.child_spec/2` no longer being part of the project. I tried getting it setup, but because of the way the `Mongo.Topology` module works, I am currently unsure how to get it working. I am also looking into this.

Aside from those two issues, if this could get a review, it would be appreciated.

**Edit**

Also about the three mongo servers that the tests spin up. Should we continue doing this, or is this something that we should defer to the developers?

**Comment by ericmj** [comment]
> Also about the three mongo servers that the tests spin up. Should we continue doing this, or is this something that we should defer to the developers?

It would be convenient to do it. Is there a way to close the servers when the tests are done? If not I think we should leave it up to the developer but provide the script that spins everything up.

**Comment by ankhers** [comment]
There are `start_mongo.bash` and `stop_mongo.bash` scripts that will start and stop the servers respectively.

**Comment by ericmj** [comment]
If you start the mongod instances from elixir without forking they should shut down when the tests are done and elixir closes. You can take a look at https://github.com/hexpm/hex/blob/master/test/support/hexpm.ex#L56-L99 for an example of starting an external program when running tests.

**Comment by ankhers** [comment]
@ericmj When I do that with mongo, the instances stay around after the tests complete. My code is,

```elixir
mongod = System.find_executable("mongod")

for i <- [1,2,3] do
    File.mkdir_p("tmp/db#{i}")
    Port.open({:spawn_executable, mongod}, [
                :exit_status,
                :use_stdio,
                :stderr_to_stdout,
                :hide,
                args: ["--dbpath", "tmp/db#{i}", "--logpath", "tmp/db#{i}/log", "--port", "2700#{i}", "--bind_ip", "127.0.0.1", "--replSet", "mongodb_test"]
              ])
end
```

I have also tried wrapping each `Port.open/2` in a `spawn_link/1` like you have shown. Neither seem to work for me.

**Comment by ericmj** [comment]
@ankhers You can try this also: https://hexdocs.pm/elixir/Port.html#module-zombie-processes

**Comment by ghost** [comment]
I'll leave this to you and close #93. Thanks for the work!

**Comment by christianjgreen** [comment]
Nice work guys! What is left that the community could possibly help out with to get this merged?

**Comment by ankhers** [comment]
Mostly testing to make sure that it works properly, or at least well enough as a starting point. 

I am still trying to figure out a way to put the `child_spec/2` function back in which would allow this driver to continue working with the `mongodb_ecto` package. Though, if I am unable to think of something relatively shortly, I will just merge this and figure it out another time.

**Comment by ericmj** [comment]
@ankhers How come this does not work?

```elixir
def child_spec(opts, child_opts \\ []) do
  DBConnection.child_spec(Mongo.Topology, opts, child_opts)
end
```

**Comment by ankhers** [comment]
Because `db_connection` package expects the module passed in to define a [`connect/1`](https://github.com/elixir-ecto/db_connection/blob/master/lib/db_connection/connection.ex#L134) function. I should be able to define it as

``` elixir
def child_spec(opts, child_opts \\ []) do
  Supervisor.Spec.worker(Mongo.Topology, [opts], child_opts)
end
```

I just need to make a couple small adjustments in the `Mongo.Topology` module for it to work this way.

**Comment by ankhers** [comment]
Alright, with that most recent commits, people should be able to test this out with `mongodb_ecto` as well if they are so inclined. Just make sure you use `{:mongodb, github: "ankhers/mongodb", branch: "server_discovery", override: true}` for your dependency. 

I'm going to test these changes in my companies staging environment, if it works out over the next day or so, I will merge this into master. 

I would prefer to use the `db_connection` package as we were prior, but that can be explored at a later point.

**Comment by christianjgreen** [comment]
Currently receiving the following stack trace when connecting to a sharded DB over ssl
Using: `seeds: ["server1.net:27017", "server2.net:27017", "server3.net:27017"]`
```
[error] GenServer #PID<0.773.0> terminating
** (UndefinedFunctionError) function :invalid_message.exception/1 is undefined (module :invalid_message is not available)
    :invalid_message.exception([])
    (db_connection) lib/db_connection.ex:926: DBConnection.checkout/2
    (db_connection) lib/db_connection.ex:742: DBConnection.run/3
    (db_connection) lib/db_connection.ex:1133: DBConnection.run_meter/3
    (db_connection) lib/db_connection.ex:636: DBConnection.execute/4
    (mongodb) lib/mongo.ex:457: Mongo.direct_command/3
    (mongodb) lib/mongo/monitor.ex:77: Mongo.Monitor.call_is_master/1
    (mongodb) lib/mongo/monitor.ex:91: Mongo.Monitor.is_master/2
    (mongodb) lib/mongo/monitor.ex:68: Mongo.Monitor.check/1
    (stdlib) gen_server.erl:601: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:667: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:EXIT, #PID<0.772.0>, {:undef, [{:invalid_message, :exception, [[]], []}, {DBConnection, :checkout, 2, [file: 'lib/db_connection.ex', line: 926]}, {DBConnection, :run, 3, [file: 'lib/db_connection.ex', line: 742]}, {DBConnection, :run_meter, 3, [file: 'lib/db_connection.ex', line: 1133]}, {DBConnection, :execute, 4, [file: 'lib/db_connection.ex', line: 636]}, {Mongo, :direct_command, 3, [file: 'lib/mongo.ex', line: 457]}, {Mongo.Monitor, :call_is_master, 1, [file: 'lib/mongo/monitor.ex', line: 77]}, {Mongo.Monitor, :is_master, 2, [file: 'lib/mongo/monitor.ex', line: 91]}, {Mongo.Monitor, :check, 1, [file: 'lib/mongo/monitor.ex', line: 68]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 601]}, {:gen_server, :handle_msg, 5, [file: 'gen_server.erl', line: 667]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}}
State: {:state, #PID<0.774.0>, [#PID<0.784.0>, #PID<0.783.0>, #PID<0.782.0>, #PID<0.781.0>, #PID<0.780.0>, #PID<0.779.0>, #PID<0.778.0>, #PID<0.777.0>, #PID<0.776.0>, #PID<0.775.0>], {[], []}, 569396, 10, 0, 0, :fifo}
```

**Comment by ankhers** [comment]
Unfortunately this PR only supports replica sets, not shards. That is going to have to be another task.

**Comment by christianjgreen** [comment]
@ankhers receiving the same error message when using a non-sharded 3 node replica set.
["host-0-0.net:27017", "host-0-1.net:27017", "host-0-2.net:27017"]

**Comment by christianjgreen** [comment]
Seems to be an issue with Poolboy: https://github.com/ericmj/mongodb/issues/94
Was fixed in this commit: https://github.com/ericmj/mongodb/commit/8b5d11f641bebe5f246a930c013471031ad2fa08

**Comment by ankhers** [comment]
@Arthien Does it work properly for you if you merge latest master into this branch?

**Comment by christianjgreen** [comment]
@ankhers It does not

**Comment by ankhers** [comment]
I will take a look at it a little later.

**Comment by ankhers** [comment]
@Arthien Is this happening only when you attempt to make a query, or is this happening even if you do nothing at all?

**Comment by ankhers** [comment]
@Arthien Can you please pull my latest change and let me know if that fixes your issue?

**Comment by christianjgreen** [comment]
Seems to be working! I will run some tests with node discovery.

**Comment by ankhers** [comment]
@Arthien (or anyone else testing) Any issues? This has been quite stable for me in staging for a couple days at this point.

**Comment by ankhers** [comment]
Thank you everyone who helped out with this!

**Pull request merged**
