### PR TITLE
WIP: Sessions and transactions support

### PR DESCRIPTION
**Pull request by hauleth**
- [x] Sessions
- [x] Transactions
- [x] Write concern
- [x] Read concern
- [ ] Retryable writes
- [ ] Casual consistency

---

Non goals:

- Session pooling

### CODE REVIEW

**Comment by deadtrickster** [comment]
https://github.com/mongodb/mongo/blob/master/jstests/core/txns/multi_statement_transaction.js leaving this link here for myself

**Comment by ankhers** [comment]
Just wanted to checkin on this. Is it still being worked on? Is there anything I can do to help?

**Comment by deadtrickster** [comment]
I guess we managed to have some working transactions here. Would be nice to have your feedback wrt how it fits the rest of the code. Also session pooling while listed as non goal would be nice to have. ping @hauleth

**Comment by ankhers** [comment]
Just quickly going over the code, but it to be good. No real complaints. Just a couple smaller things that source level pointed out. But those can be fixed up post-merge if needed. Are you guys done with this for the time being? If so, can you explain what still needs to be done to be compliant with the specification?

**Comment by hauleth** [comment]
It is mostly done, however it will bring few non-backward compatible changes. Most importantly - it drops support for everything earlier than Elixir 1.9

**Comment by ankhers** [comment]
If you are still working on it, I can try and get it to work with older versions of Elixir once you are finished.

**Comment by deadtrickster** [comment]
@ankhers I think we should try to merge it, we have another branch for example that we would like to eventually merge too. I don't want to diverge really.

**Comment by ankhers** [comment]
So you are currently done with this and want it merged? If so, I will look at it over the next few days.

**Comment by ankhers** [comment]
Is this currently complete?

**Comment by deadtrickster** [comment]
I also fixed selection_timeout raise in kobil branch if that would help

**Comment by hauleth** [comment]
@ankhers I will try to update that as soon as I find a little bit time for that as I was involved in some other stuff recently.

**Pull request closed without merging**
