### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mabeebam**
Improved usage instructions (dep poolboy).

### CODE REVIEW

**Comment by ericmj** [comment]
This is missing the instructions for adding the dependency to `:applications` which made it break for the user in the referenced issue.

I don't like having these instructions in the readme though. Firstly because anyone using mix should know this, this would be on the same level as explaining elixir features in the readme. Secondly the version in the readme will become outdated and we will get a bunch of PRs that updates it.

**Comment by mabeebam** [comment]
Hmm,

I disagree with you. I am a newbie to elixir and had to spend some time to find out that your code deps its own adapter poolboy optionally. Simple mentioning that would have hinted me that! (That was the whole reason for me PR)

And why do you want only advanced users to use mongodb?

BTW I only reference to poolboy in `:deps` not in `:applications` and the code runs perfectly (when spawning a supervisor for a child `Mongo.IdServer`:

```
  defp deps do
    [
      {:mongodb, "~> 0.1.1"},
      {:poolboy, "~> 1.5"}
    ]
  end
```

```
  def application do
    [
      applications: [..., :mongodb] # no poolboy referenced
    ]
  end
```

Updating the readme is only necessary when version numbers are explicitly defined. In case that is your concern, you can take my latest pull request

**Comment by ericmj** [comment]
Okay, fair enough.

Both poolboy and mongodb should be added to :applications. It works for you but it wont work in releases. The dependency specification is invalid now unfortunately, can you amend it to `{:dep, ">= 0.0.0"}`? Also, please squash into a single commit.

Thank you.

**Comment by mabeebam** [comment]
Hi @ericmj,

Thanks for mentioning that I need both deps for release and pointing out my invalid dependency spec.
I now use your proposed correction `{:dep, ">=0.0.0"}` and squashed my commits.
Hope I could contribute something to your project!

**Pull request merged**
