### PR TITLE
Conversion functions for Elixir 1.3+ native DateTimes

### PR DESCRIPTION
**Pull request by lau**
Add functions for converting between BSON.DateTime structs and Elixir 1.3+ native DateTimes.

### CODE REVIEW

**Comment by ericmj** [comment]
This looks good.

I think we should drop `BSON.DateTime` completely now that we have native datetimes but I am also a bit afraid of how much code it will break.

**Comment by ankhers** [comment]
For whatever it is worth, removing `BSON.DateTime` should have a minimal affect on `mongodb_ecto`. The branch supporting ecto 2 has still not been merged which would allow us to support elixir provided date times on actual release. I would also expect some breaking changes going from an adapter that supported version 1 to version 2.

I am in favour of removing `BSON.DateTime`.

**Comment by lau** [comment]
Yes, removing `BSON.DateTime` will break a bunch of code. How about changing the major release version (to 3.0) for the version completely removing `BSON.DateTime`?

A release (2.x) could support both `BSON.DateTime` and to some extent native `DateTime`. This way there is a "stepping stone" version which should make transitioning easier. I made a commit in a different branch (untested) for encoding `DateTime`s: https://github.com/lau/mongodb/commit/d311d4c0ac8574a4bc053b480ff1ddc29ff56980 

I was thinking about having a config option for choosing between decoding to `BSON.DateTime` or `DateTime`, but am guessing that reading the config at runtime every time would hurt performance too much. But supporting just encoding of `DateTime` (in addition to `BSON.DateTime`) in a 2.x version and still decoding fields from mongo to `BSON.DateTime` could be helpful too.

**Comment by ankhers** [comment]
How much code would actually break? This project only provides conversion functions for `BSON.DateTime`s.

However, releasing a version that supports both elixir `DateTime` and `BSON.DateTime` (v0.2.1?), then removing `BSON.DateTime` (v0.3.0?) is not a bad idea. On the other hand, since this is still a pre 1.0 project, changing the types and API is fairly common.

**Comment by lau** [comment]
@ankhers I have created https://github.com/ericmj/mongodb/issues/121 to discuss removing BSON.DateTime. This way this PR can be focused on adding these functions for an intermediate release that does not break existing code using BSON.DateTime.

Just looking at this PR, is anyone against merging it? Does it need any changes?

**Comment by AdamBrodzinski** [comment]
from my perspective as a consumer I would welcome the breaking change, as it's fairly easy to search/replace. I currently am converting them to datetime anyhow.

**Comment by michalmuskala** [comment]
I'm :+1: on adding those functions, I'll comment on removal in https://github.com/ericmj/mongodb/issues/121

**Comment by ericmj** [comment]
Thank you @lau!

**Comment by lau** [comment]
@ericmj Thank you!

**Pull request merged**
