### PR TITLE
Add admin_command function

### PR DESCRIPTION
**Pull request by sauvainr**
Adding a helper function to do admin command operation as creating or dropping collections.

### CODE REVIEW

**Comment by ankhers** [comment]
What does this add that the current `Mongo.command/3` does not already do?

**Comment by sauvainr** [comment]
Mostly it targets `:write` instead of `:read` which I suppose force to target the primary node.
I havn't tested with :read while preference are set to `:secondary` however it seems a bit odd.
Maybe the original command could target `:write` ?

**Comment by ankhers** [comment]
Right. I missed that the first time. I am not sure if we can switch it to target write. Maybe we can default to `:read` and give an option to switch to `:write` if necessary.

Let me think about this for a little while.

**Comment by ankhers** [comment]
After going through the code again, I don't think this is necessary. The current `Mongo.command/3` function defaults to read preference `:primary`, so it should hit the primary node unless you specifically tell it that it is okay to hit a secondary.

I just tested this and it worked as described above. I created and deleted a user giving no `:read_preference` option and it worked. I then tried to create a user passing in a `:read_preference` stating that I want it to hit `:secondary` and it failed because it cannot write to a non-master.

**Pull request closed without merging**
