### PR TITLE
Add LDAP Auth for MongoDB Enterprise

### PR DESCRIPTION
**Pull request by churchie317**
See #296.

### CODE REVIEW

**Comment by ankhers** [comment]
Thank you for this! I will release the new 0.4.8 version tomorrow.

**Comment by churchie317** [comment]
Sorry, was on vacation. Thank you for this!

**Comment by ankhers** [comment]
I got busy and forgot to push the 0.4.8 version, do you still need it?

**Comment by churchie317** [comment]
Ah, hadn’t checked yet. It would be immensely helpful if you could!

**Pull request merged**
