### PR TITLE
replica set support, travis Erlang 18 support and handle BSON.Regex option is nil

### PR DESCRIPTION
**Pull request by mingchuno**
- replica set support
- travis Erlang 18 support
- handle BSON.Regex option is nil

### CODE REVIEW

**Comment by ericmj** [comment]
Looks good. Can you add tests for the replica fallback?

**Comment by mingchuno** [comment]
@ericmj How to add tests for replica set replica fallback? Even I can set it up and run test on my local. How do we config in Travis?

**Comment by ericmj** [comment]
If you set it up to run locally I can make it work on travis.

**Comment by tjsousa** [comment]
Assuming a setup similar to the [ReplicaSet instructions for localhost](https://docs.mongodb.org/manual/tutorial/deploy-replica-set-for-testing/), I tested the following test on both branches:

``` elixir
  defp connect_slave do
    assert {:ok, pid} =
           Connection.start_link(hostname: "localhost", port: 27018, database: "mongodb_test")

    pid
  end

  test "reconnect to primary" do
    pid = connect_slave()
    coll = unique_name

    capture_log fn ->
      insert = &Connection.insert(&1, coll, %{foo: 42}, [])
      assert {:error, _} = insert.(pid)
      :timer.sleep(1000) # After the backoff it will automatically connect to master
      assert {:ok, _} = insert.(pid)
    end
  end
```

The following results show that the solution seems to work as expected:

Master:

```
...................................

  1) test reconnect to primary (Mongo.ConnectionTest)
     test/mongo/connection_test.exs:32
     match (=) failed
     code: {:ok, _} = insert.(pid)
     rhs:  {:error, %Mongo.Error{code: 10058, message: "not master"}}
     stacktrace:
       test/mongo/connection_test.exs:40: anonymous fn/1 in Mongo.ConnectionTest.test reconnect to primary/1
       test/test_helper.exs:36: MongoTest.Case.capture_log/1
       test/mongo/connection_test.exs:36

.........

Finished in 3.6 seconds (2.0s on load, 1.6s on tests)
45 tests, 1 failure

```

PR:

```
..............................................

Finished in 3.4 seconds (2.1s on load, 1.3s on tests)
46 tests, 0 failures
```

**Comment by tjsousa** [comment]
Opened a PR to the forked repository with the spec: https://github.com/mingchuno/mongodb/pull/1

**Comment by mingchuno** [comment]
I have merged the PR in my fork

**Comment by mingchuno** [comment]
need to update travis so that build can pass

**Comment by ericmj** [comment]
This needs to be rebased against master and there seems to be failing tests.

**Comment by mingchuno** [comment]
@ericmj rebase to master is not a problem, but the test fail is due to the additional test added on testing replica set functionality.

**Comment by ericmj** [comment]
Should the test be removed in that case? Why is it failing?

**Comment by mingchuno** [comment]
@ericmj check out this:
https://github.com/ericmj/mongodb/pull/47/commits/25ac5f0c4aa9f4851cdbf20b8db5b5c5935bab2b

**Comment by ericmj** [comment]
I don't follow. This PR has a single test for the replica set failovers and it is failing. The test either needs to be fixed or replaced with working tests.

**Comment by mingchuno** [comment]
@ericmj do we have replica set  set up in CI?

**Comment by ericmj** [comment]
No we don't have that yet since this is the first time replica sets logic is implemented.

**Comment by mingchuno** [comment]
@ericmj I think that's why the logic fail in the test. It assume you have mongodb rs setup in testing env.

**Comment by tjsousa** [comment]
@ericmj In fact, the specific tests that target the replica set support are failing since the MongoDB instance that is configured in Travis is not replica set aware.

I didn't dwelve into the details of setting up Travis to work with a replica set but that's what we're still missing in this PR. I followed [these instructions](https://docs.mongodb.org/manual/tutorial/deploy-replica-set-for-testing/) to set up one locally but I am not acquainted with Travis to know if it would be possible.

PS: [Does not seem pretty](http://georgeshank.com/how-to-enable-a-mongodb-replica-set-on-travis/), but something similar had been done. I can try to play with it when I get some time.

**Comment by emerleite** [comment]
This PR will be integrated? I also need replica set. +1 to integrate it.

**Comment by ericmj** [comment]
We can merge it if someone is willing to do the work to set it up on travis ci.

**Comment by emerleite** [comment]
Hi folks. I'm very interested on this PR, since I need it for my project, but I did not seem any references for Replica Set on Travis CI.

Does anybody has any information on this?

**Comment by mingchuno** [comment]
@emerleite ya, I dont see any references for Replica Set on Travis CI. So kinda stuck here....

**Comment by ericmj** [comment]
A generic solution cannot be used since we need a multitude of different replica configurations. I would suggest looking at how other mongo drivers are tested.

Also, unfortunately this PR is unlikely to be merged since it's incompatible with https://github.com/ericmj/mongodb/pull/52.

**Comment by emerleite** [comment]
Closed?

**Comment by ericmj** [comment]
It's been open since Feb 23 with no solution. If you a solution to the testing problem please open up a new PR and do it against this branch https://github.com/ericmj/mongodb/tree/emj-dbconn.

**Comment by emerleite** [comment]
Found this - http://georgeshank.com/how-to-enable-a-mongodb-replica-set-on-travis/, but not sure if it works.

**Pull request closed without merging**
