### PR TITLE
WIP: Implement Server Discovery and Monitoring and Server Selection Specs, Alternative to #67

### PR DESCRIPTION
**Pull request by chowevtfy**
In an effort to begin documentation and discussion on this implementation as early as possible, I've decided to open this early WIP pull request.

_[EDIT: turns out all of that PR needs to be rewritten, oh well]_
This is an alternative to #67 to implement the specifications below:

https://github.com/mongodb/specifications/blob/master/source/server-discovery-and-monitoring/server-discovery-and-monitoring.rst
https://github.com/mongodb/specifications/blob/master/source/server-selection/server-selection.rst

The problems with pull request #67 are that it does not comply to the above official specifications and that it doesn't include tests that work on Travis CI. We hope to address both of these issues with this pull request, but we are currently just starting the implementation. Expect more to come over the next couple of days.

### CODE REVIEW

**Comment by chowevtfy** [comment]
My current to-do list:
- [x] Use ping instead of isMaster for DBConnection pings
- [x] Connection pools for each server in topology
- ~~Clearing connections~~ not required and would need DBConnection support...
- [x] Connections for monitors don't need idle ping
- [x] https://github.com/mongodb/specifications/blob/master/source/server-discovery-and-monitoring/server-discovery-and-monitoring-monitoring.rst
- [x] ~~Restructure topology/monitor/connection process tree~~ this turned out to be too complex
- [x] Remove all ping functionality... The spec disallows it.

**Comment by chowevtfy** [comment]
Although this PR says there are conflicts, I think this will be resolved with a squash commit when I'm done. The commit that is currently causing the conflict isn't relevant to my branch.

**Comment by chowevtfy** [comment]
Some more to-do's:
- [x] remove auth for monitors
- [x] move data manipulation to TopologyDescription
- [x] manage DBConnections and Monitors from Topology
- [x] ~~attempt to restart monitors that die~~ no, the spec already deals with those failures
- [x] add support for specifying the database per-request
- [x] calculate read preference in client

**Comment by chowevtfy** [comment]
I have just tested the first successful insert using server selection for a replica set! I still need to complete writing tests and fixing several spec violations before this pull request is ready, but it is coming along nicely!

**Comment by ericmj** [comment]
db-conn has been merged into master and we will have new release out shortly. You can rebase this PR against master. What else is needed to finish this?

**Comment by ghost** [comment]
This still needs support for sharding configurations and more test coverage.  I'll rebase it and see if I can get it ready to merge for that release this weekend, along with #79.

**Comment by ghost** [comment]
Sorry, really busy right now. I'll try to get to this again next weekend.

**Comment by ericmj** [comment]
@cjhowe No worries. If I get some free cycles I will release what we have in master currently and then we can add your changes in another release. That way we will also give smaller incremental changes to the users instead of one big breaking change.

**Comment by chowevtfy** [comment]
Alright, I've rebased this branch against master. Did a squash as well. Gonna start testing and refactoring in preparation for review.

**Comment by scottmessinger** [comment]
@ericmj I noticed that the only version of Mongodb that this fails on is 2.4. With 3.4 out today, 2.4 is now 5 versions behind and almost 3 years old. When I did the `findAndModify` work, I also ran into problems with 2.4. I'm wondering if it's worth continuing to support 2.4 given the difficulty we've had with some tests, it's age, and how many versions old it is. Are many people still on 2.4? Is it worth dropping support in the next version?

**Comment by ghost** [comment]
@scottmessinger I'll be adding 2.4 support shortly, it's actually halfway done right now. I asked @ericmj the same question on Slack a while back, and he decided to keep supporting 2.4.

**Comment by chowevtfy** [comment]
Will re-open shortly.

**Comment by AdamBrodzinski** [comment]
@cjhowe @chowevtfy Just wondering if there's anything I can do to help or test? I'm currently using Mongo without replica sets and would love to use this in the future.

**Comment by InoMurko** [comment]
Use the erlang mongodb driver and write a wrapper around it.

**Comment by ghost** [comment]
There's a new PR, check that out. Also, about what @InoMurko, we actually tried that first and had some issues with it. YMMV.

**Pull request closed without merging**
