### PR TITLE
SSL compatibility

### PR DESCRIPTION
**Pull request by ankhers**

### CODE REVIEW

**Comment by Exegetech** [comment]
I'm wondering where do you put the SSL certificate?

**Comment by ankhers** [comment]
I had a brief conversation with @christiansakai in slack. The basics of the conversation are that this PR is will a work in progress. The single commit here is responsible for changing how the library uses the socket. 

Previously it was always assumed to be a `:gen_tcp` socket, so it just explicitly called the methods on that module. Now it can be one of `{:gen_tcp, socket}` or `{:ssl, socket}`. Or, more generally, `{module, socket}`. This allows us to call `module.send(socket, data)` and it automatically gets routed to the proper module.

As for specifying the SSL cert you need to use in order to authenticate against your mongo instance, that has not yet been implemented. Things like that will be added after I have successfully connected to my mongo servers that do not require an additional cert. Though, it will most likely be a `:ssl_opts` key in the argument that you pass to `Mongo.start_link/1`.

**Comment by ankhers** [comment]
@ericmj This should be good to merge as of now. The only thing that you may want to do is disable the ssl test by default (I'm not sure how many people would have SSL enabled on their dev machines. 

I am willing to do this if that is the route you want to go.

**Comment by ankhers** [comment]
Actually, this could probably use some documentation as well. Let me add that before anything else.

**Comment by ericmj** [comment]
> The only thing that you may want to do is disable the ssl test by default (I'm not sure how many people would have SSL enabled on their dev machines.

Nah, keep it. The tests seems to be failing on travis though.

**Comment by ankhers** [comment]
That looks like only the SSL test. Should I try and disable that test for travis, or see if we can generate a pem file to be used on travis?

**Comment by ericmj** [comment]
> That looks like only the SSL test.

It looks like it's crashing in the error handling after crashing, so you should look into that.

> Should I try and disable that test for travis, or see if we can generate a pem file to be used on travis?

We should try to test it on travis.

**Comment by ankhers** [comment]
So after failing a bunch of times to get an SSL version of mongo on travis, I took a look through at what the official Ruby driver is doing to test SSL connections. As it turns out, [they don't](https://github.com/mongodb/mongo-ruby-driver/blob/master/spec/spec_helper.rb#L165-L170). As much as I would like to have the test running for this, I'm not sure if it is practical.

@ericmj If you can think of a way to do it, I am open to input (or from anyone else for that matter). But as it stands I think I'm just going to revert the last handful of commits that change travis and call it good.

**Comment by Exegetech** [comment]
@ankhers thanks for the great work! CMIIW, in the `:ssl_opts` , it should be the `:cacert` or `:cacertfile` (using CA cert) correct? Because you are passing the ssl options directly to the erlang `:ssl.connect`

**Comment by ankhers** [comment]
@christiansakai It is actually `:cacerts` or `:cacertfile`. All available options can be found at http://erlang.org/doc/man/ssl.html.

**Comment by ericmj** [comment]
> So after failing a bunch of times to get an SSL version of mongo on travis, I took a look through at what the official Ruby driver is doing to test SSL connections. As it turns out, they don't. As much as I would like to have the test running for this, I'm not sure if it is practical.

Okay, thanks for trying. Can you add instructions to the readme for how to setup your server to run with ssl? (I guess it's just the mongod flags)

**Comment by ankhers** [comment]
* I added a bit of information to the README that tells you either how to exclude the SSL tests, or how to setup mongo to use SSL
* I disabled the SSL tests on Travis (or anything else that has the environment variable `CI=true`)
* Added 3.4 to the supported versions (Also added 3.4 to the travis matrix)

**Comment by ankhers** [comment]
I feel like I should share my current problem just incase anyone else comes across this issue.

I am having an issue with the underlying Erlang SSL library where it attempts to connect to a specific server, I am getting `{:error, {:tls_alert, 'handshake failure'}}` even though I know the server is using a valid certificate. There is nothing this driver can do to solve this problem.

With that said, I can connect to every other Mongo instance that I have attempted to connect to. So this PR is working.

I have [emailed the erlang-questions](http://erlang.org/pipermail/erlang-questions/2016-December/091181.html) mailing list for help. Hopefully someone will be able to help me figure out why this is happening.

**Comment by ankhers** [comment]
Just a quick update with my SSL issue.

Ingela from the OTP team was kind enough to help me solve my problem. It turns out the certificate I was trying to authenticate was too big. When the Erlang code would reach the point of checking the handshake information, normally there would be at least one handshake packet. But because of the length of my certificate, there was not handshake packet yet to verify.

This has been "fixed" in the sense that Ingela wrote a patch. The release for this fix depends on how important the OTP team deems this issue to be.

**Review by ericmj — APPROVED** [review]
This looks good to me. @ankhers anything you want in before merging?

**Comment by ankhers** [comment]
@ericmj I think it should be good at this point.

**Comment by ericmj** [comment]
Thank you!

**Comment by christianjgreen** [comment]
@ankhers @ericmj It looks like OTP release 19.3 fixed this issue. Will be closing #117 

Thanks!

**Pull request merged**
