### PR TITLE
Replace BSON.DateTime with native Elixir DateTime

### LINKED ISSUE #121: Remove BSON.DateTime and replace with DateTime
This issue is for discussing removing `BSON.DateTime` and replacing it with `DateTime`.

Creating this issue so that https://github.com/ericmj/mongodb/pull/120 discussion can be about just the PR to add functions for native Elixir`DateTime` structs without removing `BSON.DateTime.`

### PR DESCRIPTION
**Pull request by lau**
Closes #121

### CODE REVIEW

**Comment by ericmj** [comment]
Great, thank you @lau. I think we could release a new version now and then start 0.3.0 with this change and the replica support. What do you think @ankhers?

**Comment by ankhers** [comment]
I think that is a good plan. Though, I want to hold out on the Replica Set stuff for just a little while.

@ericmj If you have time, go ahead and make the release. If you don't I will have time either tonight or tomorrow morning.

**Comment by ericmj** [comment]
> I think that is a good plan. Though, I want to hold out on the Replica Set stuff for just a little while.

Right, 0.3.0 will be ready when it's ready. I just meant that master could be used for replica sets after we have a release out. But that's up to you of course.

**Comment by lau** [comment]
How long will it take for the replica set stuff to be done? Would it make sense to release 0.3.0 with DateTime first and then 0.4.0 with replica set?

**Comment by ankhers** [comment]
I unfortunately do not have an exact time frame on Replica Sets. There is an active PR up for it (#124). There is still work that needs to be done on it though. I will most likely release 0.3.0 before RS is supported.

**Comment by ankhers** [comment]
Thanks!

**Pull request merged**
