### PR TITLE
Support BSON symbol type

### PR DESCRIPTION
**Pull request by jocko**
Add support for decoding BSON symbol fields. Also, atoms will be encoded as symbols (instead of strings).

### CODE REVIEW

**Comment by ericmj** [comment]
What's the motivation for adding this? It's deprecated in the bson specification and is just called string instead of symbol.

http://bsonspec.org/spec.html

**Comment by jocko** [comment]
Yeah, I know that it is deprecated. Don't know what that means exactly though. We already have data in our production database with fields encoded as symbols. At the very least, I need to be able to decode them. 

When it comes to encoding atoms as symbols instead of strings, I can live without that. The reason for doing that is that I think it is a bit confusing to persist a hash with atom values only to get it back as a string value when you do a find at a later moment.

**Comment by ericmj** [comment]
Sorry for the late response, I've been thinking about the best way of solving this.

First off I would suggest normalizing your database by converting all symbols to strings. We can add decoding of symbols into strings. But I will not add encoding of atoms into symbols since atoms are very common in elixir and symbols are deprecated in BSON, adding that would just mean that we would be inserting deprecated values all the time.

Please update the PR by removing the encoding and add test that makes sure that encoding atoms will result in a BSON string. Thank you!

**Comment by jocko** [comment]
No problems. Reverted the encoding stuff (other than adding a test for it as requested).

**Comment by ericmj** [comment]
@jocko Thank you!

**Pull request merged**
