### PR TITLE
remove/comment never used module attributes

### PR DESCRIPTION
**Pull request by deepblue**
Found the below warnings:

```
warning: module attribute @op_reply was set but never used
  lib/mongo/messages.ex:17

warning: module attribute @reply_flags was set but never used
  lib/mongo/messages.ex:48
```

### CODE REVIEW

**Comment by ericmj** [comment]
You can actually remove it instead of commenting it and remove the comment below that references the module attribute. Thank you!

**Comment by deepblue** [comment]
@ericmj code removed instead of commenting. Thanks for the review!

**Comment by ankhers** [comment]
@deepblue Would you mind rebasing these 2 commits into a single one?

**Comment by ericmj** [comment]
@ankhers You can squash by selecting it in the dropdown list when merging.

**Comment by ankhers** [comment]
Thanks!

**Pull request merged**
