### PR TITLE
Fix dialyzer

### PR DESCRIPTION
**Pull request by gpad**
Fix some specs and some small bug that dialyzer discover. I added also the dialyzer task on travis only on elixir version 1.6.

### CODE REVIEW

**Comment by ankhers** [comment]
There was quite a bit of code that was commented out. Would you be able to remove it instead if it was not used?

**Comment by gpad** [comment]
@ankhers Removed all the dead code ...

**Comment by gpad** [comment]
@ankhers I have update my PR with master let me know WDYT or If I can help you in other way ...

**Comment by ankhers** [comment]
Thanks! I'm just waiting for travis to do it's thing and when it passes I will be merging.

**Comment by ankhers** [comment]
Thank you!

**Pull request merged**
